# Generated by Django 2.0.3 on 2018-10-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181005_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='OnPizza',
        ),
        migrations.AddField(
            model_name='toppings',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Pizza'),
        ),
    ]
