# Generated by Django 2.0.3 on 2018-10-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181005_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='price',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ToppingCost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
