# Generated by Django 2.0.3 on 2018-10-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181006_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='pizza',
            field=models.ManyToManyField(blank=True, null=True, related_name='toppings', to='orders.Pizza'),
        ),
    ]
