# Generated by Django 2.0.3 on 2018-10-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181006_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='ForOrder',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='toppings',
            name='pizza',
        ),
        migrations.AddField(
            model_name='toppings',
            name='fk_pizza',
            field=models.ManyToManyField(blank=True, to='orders.Pizza'),
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
