# Generated by Django 2.0.3 on 2018-10-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20181007_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'pizza', 'verbose_name_plural': 'pizzas'},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name': 'topping', 'verbose_name_plural': 'toppings'},
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ToppingCost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='large',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='small',
            field=models.IntegerField(),
        ),
    ]
