# Generated by Django 2.0.3 on 2018-10-21 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_auto_20181010_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='orders',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='fk_User',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='zip',
            field=models.CharField(default='11235', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='fk_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Orders'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='fk_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza'),
        ),
    ]
