# Generated by Django 2.0.3 on 2018-10-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_orders_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='created_on',
        ),
    ]
